experiment:
  exp_name: dynamic_nomix_str08_smallFit
  exp_comment: Wdecay_LR6_Exponential
  exp_fullname: ${.exp_name}_${.exp_comment}
  ckpt_path: ./exps/${.exp_name}/${.exp_comment}/ckpt.pth.tar # load from *.best, save to *
  board_dir: ./exps/${.exp_name}/${.exp_comment}

strategy: dynamic_mix
# static_old, static_new, static_mix, dynamic_mix

optimizer:
  batch_size: 6
  weight_decay: 5e-3
  lr: 1e-8  # for OneCycle and Cosine, this is the max_lr

schedule:
  num_epoch: 10
  schedule_policy: OneCycle # Cosine, Plateau, OneCycle, Exponential
  verbose: True
  val_freq: 1
  test_only: True

distributed:
  toggle: False
  server:
    host: localhost
    port: 3471 # change this if has conflict
    url: 'tcp://${.host}:${.port}'

dataset:
  small_fit: 0 # 1 for True, 0 for False
  size: 380 # transformation
  folds_json_path: folds.json
  root_dir: data/
  crops_dir: crops
  output_dir: weights/
  load_workers: 0 # multi-process data loading
