experiment:
  exp_name: dynamic
  exp_comment: Wdecay_LR6_Plateau_L
  exp_fullname: ${.exp_name}_${.exp_comment}
  ckpt_path: ./exps/${.exp_name}/${.exp_comment}/ckpt.pth.tar # load from *.best, save to *
  board_dir: ./exps/${.exp_name}/${.exp_comment}

strategy: static_new
# static_old, static_new, dynamic_baseline

optimizer:
  batch_size: 6
  weight_decay: 5e-3
  lr: 1e-6  # for OneCycle and Cosine, this is the max_lr

schedule:
  num_epoch: 100
  schedule_policy: Plateau # Cosine, Plateau, OneCycle, Exponential
  verbose: True
  val_freq: 1

distributed:
  toggle: True
  gpu_workers: 4 # spawn mode only
  server:
    host: localhost
    port: 4471
    url: 'tcp://${.host}:${.port}'

dataset:
  small_fit: 0 # 1 for True, 0 for False
  size: 380 # transformation
  folds_json_path: folds.json
  root_dir: data/
  crops_dir: crops
  output_dir: weights/
  load_workers: 0 # multi-process data loading