experiment:
  exp_name: static_lr1e6
  ckpt_path: $./exps/${.exp_name}/ckpt1.pth.tar
  board_dir: $./exps/${.exp_name}/log
  seed: 4471

optimizer:
  batch_size: 6
  weight_decay: 0.001
  lr: 1e-6

schedule:
  num_epoch: 30
  schedule_policy": Plateau # Cosine, Plateau, OneCycle, Exponential

distributed:
  toggle: True
  gpu_workers: 4 # spawn mode only
  server:
    host: localhost
    port: 4471
    url: 'tcp://${.host}:{.port}'

dataset:
  propotion: 1 # 0.1, 0.5, 1(Full)
  size: 380
  fold: 0
  folds_csv_path: folds.csv
  folds_json_path: folds.json
  root_dir: data/
  crops_dir: crops
  output_dir: weights/
  load_workers: 1